// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYGxxhAECHXtgIOx3WtXx-VymblKGRC8',
    appId: '1:774375747236:web:11cff6771d99a7a7914031',
    messagingSenderId: '774375747236',
    projectId: 'mobile-c2195',
    authDomain: 'mobile-c2195.firebaseapp.com',
    storageBucket: 'mobile-c2195.firebasestorage.app',
    measurementId: 'G-91L282JQDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Uly1t53mlX9IR5a36oYKu2KQ6lqBlY8',
    appId: '1:774375747236:android:7db068a4ead38320914031',
    messagingSenderId: '774375747236',
    projectId: 'mobile-c2195',
    storageBucket: 'mobile-c2195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGoAWoXZygqxhoEmLf7MsgmGSJWy0UQU',
    appId: '1:774375747236:ios:03f1572fdd584bfc914031',
    messagingSenderId: '774375747236',
    projectId: 'mobile-c2195',
    storageBucket: 'mobile-c2195.firebasestorage.app',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbGoAWoXZygqxhoEmLf7MsgmGSJWy0UQU',
    appId: '1:774375747236:ios:03f1572fdd584bfc914031',
    messagingSenderId: '774375747236',
    projectId: 'mobile-c2195',
    storageBucket: 'mobile-c2195.firebasestorage.app',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYGxxhAECHXtgIOx3WtXx-VymblKGRC8',
    appId: '1:774375747236:web:b5a6c76cbf45e0c7914031',
    messagingSenderId: '774375747236',
    projectId: 'mobile-c2195',
    authDomain: 'mobile-c2195.firebaseapp.com',
    storageBucket: 'mobile-c2195.firebasestorage.app',
    measurementId: 'G-XYMKENZL4F',
  );
}
